[workspace]
members = [
    "shrs",
    "shrs_line",
    "shrs_lang",
    "shrs_example",
    "shrs_vi",
    "plugins/shrs_output_capture",
    "plugins/shrs_cd_tools",
    "plugins/shrs_prompt_builder",
]
